### PR TITLE
HDMI video updates

### PR DESCRIPTION
**Pull request by warped-rudi**
As discussed at ewc, here are the changes for HDMI video I got for now. They bring back support for several modes that were missing/broken in 4.9.x. This includes 1920x1080i as well as 720x480 and 720x576p. The last patch is a bit more intrusive as it introduces a more structural change. But I really disliked the idea of having three (3) different copies of basically the same parsing loop...

### CODE REVIEW

**Comment by warped-rudi** [comment]
Jon, please don't merge today. I just identified a bug in fb_var_to_videomode() and will test a fix this evening. Stay tuned...

**Comment by jnettlet** [comment]
Will do.  FYI you haven't responded to my last email.  Can you email me at my solid-run.com account to make sure I have your current email address.  Thanks.

**Comment by warped-rudi** [comment]
Strange. I did. Anyway, just re-sent it...

**Comment by warped-rudi** [comment]
O.K, the problem was with fb_find_mode(), not fb_var_to_videomode() as I thought in the first place. So you can now try and decide if you want to merge it. And I forgot to mention: DVI should also work with better resolutions than just standard VGA. Did you receive my mail from this morning?

**Comment by jnettlet** [comment]
Nice @warped-rudi   A very nice cleanup overall.  impressive work.  Thanks a lot.

**Pull request merged**
